apiVersion: apps/v1
kind: Deployment
metadata:
  name: contato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contato
  template:
    metadata:
      labels:
        app: contato
    spec: 
      containers:
      - name: contato
        image: fabaofloripa/contato:latest
        ports:
          - containerPort: 8080
  
---

apiVersion: v1
kind: Service
metadata:
  name: contato-service  
spec:
  selector:
    app: conato
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer 