apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatoapipod
  labels:
    app: contatoapipod
    environment: production
    team: dev
  annotations:
    description: "Deployment do aplicativo de contatos API"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contatoapipod
  template:
    metadata:
      labels:
        app: contatoapipod
        environment: production
        team: dev
      annotations:
        description: "Pod do aplicativo de contatos API"
    spec: 
      containers:
      - name: contatoapipod
        image: fabaofloripa/contatos.api:latest
        ports:
          - containerPort: 8080
  
---

apiVersion: v1
kind: Service
metadata:
  name: contatoapipod-service
  labels:
    app: contatoapipod
    environment: production
    team: dev
  annotations:
    description: "Service para o aplicativo de contatos API"
spec:
  selector:
    app: contatoapipod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
