apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatoapipod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contatoapipod
  template:
    metadata:
      labels:
        app: contatoapipod
    spec: 
      containers:
      - name: contatoapipod
        image: fabaofloripa/contatos.api:latest
        ports:
          - containerPort: 8080
  
---

apiVersion: v1
kind: Service
metadata:
  name: contatoapipod-service  
spec:
  selector:
    app: contatoapipod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer 
